services:
  speed_reading:
    image: ghcr.io/lifufkd/speed-reading:latest
    build: .
    restart: unless-stopped
    ports:
      - ${API_PORT:-8000}:8000
    env_file:
      - ".env"
    volumes:
      - app_data:/app/app_data
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis
    networks:
      - backend

  postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
       - POSTGRES_USER=${DB_USER:-postgres}
       - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
       - POSTGRES_DB=${DB_DATABASE:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - backend

volumes:
  postgres_data:
  redis_data:
  app_data:

networks:
  backend: