"""create field 'email' in 'users' table

Revision ID: 8297126562e4
Revises: 621b4946cb41
Create Date: 2025-06-24 18:32:32.048166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8297126562e4'
down_revision: Union[str, Sequence[str], None] = '621b4946cb41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.create_unique_constraint("users_email_key", 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_email_key", 'users', type_='unique')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
