"""add index to 'task_id' field in table 'users_tasks'

Revision ID: e4e4d6625c2a
Revises: 146b43232cab
Create Date: 2025-06-29 19:14:32.207763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4e4d6625c2a'
down_revision: Union[str, Sequence[str], None] = '146b43232cab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_tasks_task_id'), 'users_tasks', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tasks_task_id'), table_name='users_tasks')
    # ### end Alembic commands ###
