"""make login field unique in users table

Revision ID: f4646731bfce
Revises: 2b9b09915871
Create Date: 2025-06-22 18:30:55.911556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4646731bfce'
down_revision: Union[str, Sequence[str], None] = '2b9b09915871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.create_unique_constraint("users_login_key", 'users', ['login'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_login_key", 'users', type_='unique')
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=False)
    # ### end Alembic commands ###
